services:
  mariadb:
    image: mariadb:latest # 建議使用特定版本，例如 mariadb:10.6
    container_name: loginsystem-mariadb-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kk95681932 # 這是你的 root 密碼
      MYSQL_DATABASE: login_db        # 這是你的資料庫名稱
      MYSQL_USER: borlon            # 這是你的使用者名稱
      MYSQL_PASSWORD: kk95681932    # 這是你的使用者密碼
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql # 資料持久化
    ports:
      - "3307:3306" # 將主機的 3307 端口映射到容器的 3306 端口 因為本地3306 可能被mariadb佔用

  redis: # 新增 Redis 服務
    image: redis:6-alpine # 推薦使用 Alpine 版本，較小巧
    container_name: your-app-redis # 給你的 Redis 容器一個名稱
    restart: always
    ports:
      - "6379:6379" # Redis 預設端口是 6379，將主機 6379 映射到容器 6379
    volumes:
      - ./data/redis:/data # 將 Redis 資料持久化到本地，防止重啟丟失
