version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: kk95681932
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql