version: 11.2.0
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kk95681932
    volumes:
      - ./data/var/lib/mysql
    ports:
      - 3306:3306